### ISSUE TITLE
Rechtschreibfehler in Parser-Exception

### ISSUE THREAD

**Issue by oliver-zach-campus02** [MarkusKummer/fh-campus02-swe-2024#1]
Fehler im Parser @MarkusKummer @hoedlChr bitte beheben.

**Comment by hoedlChr** [comment]
@oliver-zach-campus02 reis dich zusammen

**Comment by oliver-zach-campus02** [comment]
@hoedlChr wos bistn heut so zwieda?

**Comment by hoedlChr** [comment]
# ich hab noch nichts getrunkne
